### ISSUE TITLE
yelee主题的主页右侧无显示问题

### ISSUE THREAD

**Issue by OHLIA** [judasn/judasn.github.io#1]
你好啊，
我最近在看你写的教程，
http://www.youmeek.com/，

但是我配置了yelee主题，
主页右侧却没有显示，
不知道是不是需要特别设定？
https://s1.ax2x.com/2018/03/03/cw0kG.jpg

**Comment by judasn** [comment]
1.确保那些文章类md文件存放对目录。这些文件不是随便放的。请在认真核对下文章。

**Comment by OHLIA** [comment]
都是
hexo new “名称”
生成的博客文章
目录是没问题的
